message: Hello World
spring:
    cloud:
      config:
        server:
          git:
            uri:
    profiles.active: test

server.port: 8889

db:
  connection: connection-to-test
  host: host-test
  name: test
  port: 3306

management:
  endpoints:
    web:
      exposure:
        include: "*"
